# -*- coding: utf-8 -*-
"""Global Stock Screener.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CCNYDihbDQDOKTQBSRoIvwzuS94eVI5
"""

import streamlit as st
import yfinance as yf
import pandas as pd

# Title
st.title("\U0001F30D Global Stock Screener")

# Sidebar filters
st.sidebar.header("Filter Stocks")
exchange = st.sidebar.selectbox("Select Exchange", [
    "All", "NYSE", "NASDAQ", "TSE", "LSE", "BSE", "Euronext"
])
sector = st.sidebar.selectbox("Select Sector", [
    "All", "Technology", "Healthcare", "Finance", "Energy", "Consumer"
])
price_range = st.sidebar.slider("Price Range", 0, 1000, (10, 500))

# Example stock list with sectors and exchanges
stocks = {
    "AAPL": {"name": "Apple Inc.", "exchange": "NASDAQ", "price": 190, "sector": "Technology"},
    "TSLA": {"name": "Tesla Inc.", "exchange": "NASDAQ", "price": 250, "sector": "Technology"},
    "JNJ": {"name": "Johnson & Johnson", "exchange": "NYSE", "price": 165, "sector": "Healthcare"},
    "BP.L": {"name": "BP plc", "exchange": "LSE", "price": 30, "sector": "Energy"},
    "RELIANCE.BO": {"name": "Reliance Industries", "exchange": "BSE", "price": 45, "sector": "Energy"},
    "AIR.PA": {"name": "Airbus SE", "exchange": "Euronext", "price": 134, "sector": "Consumer"}
}

# Filter logic
filtered = {
    symbol: info for symbol, info in stocks.items()
    if (exchange == "All" or info['exchange'] == exchange)
    and (sector == "All" or info['sector'] == sector)
    and price_range[0] <= info['price'] <= price_range[1]
}

# Display results
st.subheader("\U0001F4C8 Matching Stocks")
if filtered:
    for symbol, info in filtered.items():
        st.write(f"**{info['name']}** ({symbol}) – Price: ${info['price']} – Sector: {info['sector']}")
        try:
            data = yf.download(symbol, period="5d", interval="1d")
            if not data.empty:
                st.line_chart(data['Close'])
        except:
            st.write("Error fetching data for", symbol)
else:
    st.info("No stocks match your criteria.")

# PayPal donation
st.markdown("""
---
### ❤️ Support this App
If this tool helps you, consider [donating via PayPal](https://www.paypal.com/donate?hosted_button_id=YOUR_ID).
""")



